### ISSUE TITLE
docker compose install results in "serviceWorker is undefined"

### ISSUE THREAD

**Issue by Niehztog** [titaniumnetwork-dev/Ultraviolet-App#105]
Hello. I am trying to deploy my own self hosted ultraviolet app to my local docker environment using docker compose. I used the following docker-compose.yaml file:
```yaml
services:
  ultraviolet:
    image: diffusehyperion/ultraviolet
    container_name: ultraviolet-proxy
    ports:
      - "8080:8080"
    restart: unless-stopped
```
I can then access the ultraviolet server by navigating to http://192.168.0.10:8080 in firefox or chromium. But when I enter any site url in the input box and hit enter, nothing happens. The developer tools reveal a javascript error:
`Uncaught TypeError: serviceWorker is undefined`

Please advise which steps are necessary to fix this
